name: hugegraph ci

on:
  push:
    branches:
      - master
      - /^release-.*$/
      - /^test-.*$/
      - gh-master
      - gh-pre-release
      - gh-dis-release
  pull_request:
    branches:
      - master
      - /^release-.*$/
 #     - /^test-.*$/
      - gh-master
      - gh-pre-release
      - gh-dis-release

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      TRAVIS_DIR: hugegraph-dist/src/assembly/travis
      LIB_DIR: hugegraph-dist/src/assembly/travis/lib
    strategy:
      fail-fast: false
      matrix:
        BACKEND: [memory, cassandra, hbase, rocksdb]
    steps:
      - name: Install JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Compile
        run: |
          mvn install:install-file -DgroupId=com.baidu.hugegraph -DartifactId=hugegraph-common -Dversion=1.8.10 -Dpackaging=jar -Dfile=$LIB_DIR/hugegraph-common-1.8.10.jar -DpomFile=$LIB_DIR/common-pom.xml
          mvn compile -Dmaven.javadoc.skip=true | grep -v "Downloading\|Downloaded"

      - name: Prepare env and service
        run: |
          $TRAVIS_DIR/install-etcd.sh
          $TRAVIS_DIR/install-backend.sh ${{ matrix.BACKEND }}

      - name: Run test
        run: |
          mvn test -P core-test,${{ matrix.BACKEND }}
          $TRAVIS_DIR/run-api-test.sh ${{ matrix.BACKEND }}
          $TRAVIS_DIR/run-unit-test.sh ${{ matrix.BACKEND }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: target/site/jacoco/jacoco.xml
